### ISSUE TITLE
各言語の example の追加について

### ISSUE THREAD

**Issue by uttne** [labocho/drill-book#1]
各言語の example はどんな感じに追加すればいいんでしょうか？
今だと example フォルダの中に Ruby のソースが一つだけ入っていますがここに他の言語のソースを追加する感じでしょうか？

例
```
drill-book\001_hello_world\example
┣━ hello_world.rb
┗━ hello_world.c
```

**Comment by labocho** [comment]
example は参考のための Ruby 実装ですので、実装は別のディレクトリで行っていただくことを想定しています。
※ [README.md](https://github.com/labocho/drill-book/blob/master/README.md#%E9%80%B2%E3%82%81%E6%96%B9) に記載していなかったので記載しました。

ディレクトリ名や構造は言語によって慣例があると思いますので特に指定していません。下記の例のようにお好きなようにしてください。

```
例1:
drill-book/001_hello_world
┗━ hello_world.c
```

```
例2:
drill-book/001_hello_world
┗━ src
   ┗━ hello_world.c
```
